# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UDSChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UDSChallenge
 pod 'RxSwift'
 pod 'RxCocoa'
  target 'UDSChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
